name: yogamike
favicon: null
layout_spectrum: 0.14866
typography_spectrum: 0.42034
title: Mike Mirabal - Yoga
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e17628'
    - '#f2e33e'
    - '#4e799c'
    - '#1e1a1f'
    - '#7d4b23'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
