name: yogamike
favicon: null
layout_spectrum: 0.23957599722780287
typography_spectrum: 0.4220208197366446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9482054880354553
  lightness: 0.09739436488598585
  saturation: 0.05097932065837085
  rhythmicContrast: 0.9141256615985185
purpose: []
