name: yogamike
favicon: null
layout_spectrum: 0.204
typography_spectrum: 0.25236
title: Mike Mirabal - Yoga
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f241c'
    - '#ffffff'
    - '#ffd99c'
    - '#6d401a'
    - '#a6714b'
  brandStrength: 0.375
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
