name: yogamike
favicon: null
layout_spectrum: 0.14866
typography_spectrum: 0.42034
title: Mike Mirabal - Yoga
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8094a3'
    - '#fffdfe'
    - '#f0da8e'
    - '#3d3026'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
