name: yogamike
favicon: null
layout_spectrum: 0.14866
typography_spectrum: 0.42034
title: Mike Mirabal - Yoga
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dc7431'
    - '#ecedc2'
    - '#350815'
    - '#db9f4b'
    - '#791e1b'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose: []
