name: yogamike
favicon: null
layout_spectrum: 0.9462
typography_spectrum: 0.4220208197366446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#19110f'
    - '#ffffff'
    - '#a69f9a'
    - '#cbc1b8'
    - '#545255'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 1
purpose: []
